title: oraki  
description: pensamientos, escritos y rarezas personales  
email: contacto@oraki.com.mx  

author: ricardo meza  

social:
  github: ikaaro
  instagram: tu_usuario_si_quieres  

logo: /img/logo.svg  
rss: "/feed.xml"

theme_setting:
  slides_count: 4
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - 
      title: "blog"
      url: "/blog/"
  code: true
  math: false
  mermaid: false
  lang:
    category_all: Todos
    blog_title: Inicio
